spring: 
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/weixin1?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: weixin1
      password: 1234
   #显示SQL语句   
   jpa:
      show-sql:true
      generated-ddl:true
   # 配置Redis的连接信息
   redis:
      # 这里换自己的IP
      host: 120.77.251.143
      port: 6379
      database: 4